backtraces_path = "/home/plusai/tmp/neovide_backtraces.log" # see below for the default platform specific location
fork = true
frame = "full"
idle = true
maximized = true
mouse-cursor-icon = "arrow"
no-multigrid = false
srgb = false # platform-specific: false (Linux/macOS) or true (Windows)
tabs = true
title-hidden = true
vsync = true
wsl = false
opengl = true

[font]
normal = ["Maple Mono NL NF CN"]
size = 12.0

[box-drawing]
# "font-glyph", "native" or "selected-native"
mode = "font-glyph"

[box-drawing.sizes]
default = [2, 4]  # Thin and thick values respectively, for all sizes

